packer: Include Packer version in AMI tags

diff --git a/packer/build b/packer/build
--- a/packer/build
+++ b/packer/build
@@ -6,6 +6,7 @@ RC_OK=0
 RC_MISSING_ARG=10
 RC_NO_SUCH_CONFIG=11
 RC_DIRTY_REPOSITORY=12
+RC_FAILED_DETERMINING_PACKER_VERSION=13
 
 script_dir=$(dirname "$0")
 script_name="$(basename "$script_dir")/$(basename "$0")"
@@ -60,6 +61,7 @@ function packer_build_template() {
     local ami_software_version=$2
     local ami_build_number=$3
     local infra_revision=$4
+    local ami_packer_version=$5
     local ami_name="${ami_role} ${ami_software_version}-${ami_build_number}"
 
     local packer_template
@@ -80,6 +82,7 @@ function packer_build_template() {
                 "tags": {
                     "Name":                            $ami_name,
                     "johnk:ami:role":                  $ami_role,
+                    "johnk:ami:packer-version":        $ami_packer_version,
                     "johnk:ami:software-version":      $ami_software_version,
                     "johnk:ami:build-number":          $ami_build_number,
                     "johnk:ami:source-ami":            "{{ .SourceAMI }}",
@@ -108,6 +111,7 @@ EOF
         --null-input \
         --compact-output \
         --arg ami_role             "$ami_role" \
+        --arg ami_packer_version   "$ami_packer_version" \
         --arg ami_software_version "$ami_software_version" \
         --arg ami_build_number     "$ami_build_number" \
         --arg ami_name             "$ami_name" \
@@ -142,8 +146,13 @@ function main() {
         exit "$RC_DIRTY_REPOSITORY"
     fi
 
+    local packer_version=$(packer version | head -n1 | grep -Eo '([0-9]+\.)*[0-9]+')
+    if [[ -z "$packer_version" ]]; then
+        echo 'FATAL: Unable to determine Packer version.' >&2
+        exit "$RC_FAILED_DETERMINING_PACKER_VERSION"
+    fi
     local ami_build_number=$(ami_next_build_number "$AMI_ROLE" "$AMI_SOFTWARE_VERSION")
-    local packer_template=$(packer_build_template "$AMI_ROLE" "$AMI_SOFTWARE_VERSION" "$ami_build_number" "$infra_revision")
+    local packer_template=$(packer_build_template "$AMI_ROLE" "$AMI_SOFTWARE_VERSION" "$ami_build_number" "$infra_revision" "$packer_version")
     echo "$packer_template" | packer build "${packer_args[@]}" -
 }
 
